# Generated by Django 4.0.6 on 2022-07-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_dislikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
