# Generated by Django 4.0.6 on 2022-07-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ipaddress_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
