# Generated by Django 4.0.6 on 2022-07-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_articlehit_alter_article_views_delete_articleviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
