# Generated by Django 4.0.6 on 2022-07-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_alter_blockeduser_id_alter_blockeduserhistory_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted', '-edited']},
        ),
    ]
