# Generated by Django 4.0.6 on 2022-07-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='image/16410.jpg', upload_to='avatar', verbose_name='آواتار'),
        ),
    ]
